data:
  data_dir: /dev/shm/mesh/
  batch_size: 3
  num_workers: 20
  mode: cylinder
  dataset:
    time_horizon: 25
    padding: True
    max_len: 2060
    use_embed: False
  normalizer:
    use_norm: true 
    scaler: normal
    stat_path: /dev/shm/mesh/train_normal_stat.pkl
    conditional: False

training:
  accelerator: gpu
  check_val_every_n_epoch: 10
  log_every_n_steps: 32
  checkpoint: null
  dataset_size: 1000
  default_root_dir: logs/
  devices: 3
  strategy: auto
  accumulate_grad_batches: 1
  max_epochs: 1000
  seed: 42
  ema_decay: null
  ema_every_n_steps: 1

wandb:
    name: LDM_cylinder_normal_FF
    project: ldm_diffusion

model:
    base_learning_rate: 5.0e-05
    beta_schedule: linear
    cosine_s: 0.008
    linear_start: 0.00085
    linear_end: 0.012
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    image_size: 16
    channels: 16
    cond_stage_trainable: True
    scale_factor: 0.2
    clip_denoised: False
    parameterization: eps
    monitor: val/loss
    dist: True

    scheduler_config:
        scheduler: cosine
        
    model_config:
        image_size: 16
        in_channels: 16
        out_channels: 16
        model_channels: 128
        attention_resolutions:
        - 8
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 4
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 2
        context_dim: 128
        use_checkpoint: False
        legacy: False

    first_stage_config:
        pretrained_path: logs/GINO_autoencoderKL_16_normed_batched2024-07-25T12-14-31/model_epoch=974-val/rec_loss=0.01.ckpt
        aeconfig:
          decoder:
            attn_resolutions:
            - 16
            ch_mult:
            - 1
            - 2
            - 4
            double_z: true
            dropout: 0.1
            gno_coord_dim: 3
            gno_coord_embed_dim: 16
            gno_mlp_hidden_layers:
            - 64
            - 64
            - 64
            - 64
            gno_radius: 0.0425
            gno_transform_type: linear
            gno_use_torch_scatter: true
            hidden_channels: 64
            in_channels: 16
            num_res_blocks: 2
            out_channels: 3
            resolution: 64
            use_open3d: true
            z_channels: 16
            tanh_out: false
          double_z: true
          encoder:
            attn_resolutions:
            - 16
            ch_mult:
            - 1
            - 2
            - 4
            double_z: true
            dropout: 0.1
            gno_coord_dim: 3
            gno_coord_embed_dim: 16
            gno_mlp_hidden_layers:
            - 64
            - 64
            - 64
            - 64
            gno_radius: 0.0425
            gno_transform_type: linear
            gno_use_torch_scatter: true
            hidden_channels: 64
            in_channels: 3
            num_res_blocks: 2
            out_channels: 16
            resolution: 64
            use_open3d: true
            z_channels: 16
            tanh_out: false
          latent_grid_size: 64
        lossconfig:
          kl_weight: 2.0e-07

        training:
            dist: True

    cond_stage_config:
        conditional: True
        out_dim: 128
        pretrained: False
        encoder:
            attn_resolutions:
            - 8
            ch_mult:
            - 1
            - 2
            - 4
            double_z: False
            dropout: 0.0
            gno_coord_dim: 2
            gno_coord_embed_dim: 32
            gno_mlp_hidden_layers:
            - 128
            - 128
            - 128
            gno_radius: 0.05
            gno_transform_type: nonlinear
            gno_use_torch_scatter: true
            hidden_channels: 128
            in_channels: 3
            num_res_blocks: 2
            out_channels: 128
            resolution: 32
            use_open3d: false
            z_channels: 128