load_dir: logs/ns2D/
model_path: /home/ayz2/ldm_fluids/logs/ns2D/new_rec_loss=0.01.ckpt
model_name: ae

data:
    batch_size: 1
    num_workers: 4
    mode: turb3D
    drop_last: False
    dataset:
      data_dir: /pscratch/sd/a/ayz2/turb3D/data
      time_horizon: 500
      time_window: 240
      time_stride: 5
    normalizer:
      use_norm: true 
      scaler: normal
      stat_path: /pscratch/sd/a/ayz2/turb3D/turb3d_norm_stats.pkl

model:
    aeconfig:
      encoder:
        attn_resolutions:
        - 16
        ch_mult:
        - 1
        - 2
        - 2
        - 4
        double_z: true
        dropout: 0.0
        hidden_channels: 64
        in_channels: 4
        num_res_blocks: 2
        out_channels: 32
        resolution: [48, 96, 24, 24]
        z_channels: 32
        tanh_out: false
        dim: 4
      decoder:
        attn_resolutions:
        - 16
        ch_mult:
        - 1
        - 2
        - 2
        - 4
        double_z: true
        dropout: 0.0
        hidden_channels: 64
        in_channels: 32
        num_res_blocks: 2
        out_channels: 4
        resolution: [48, 96, 24, 24]
        z_channels: 32
        tanh_out: false
        dim: 4
    lossconfig:
      kl_weight: 2.0e-07

training:
  seed: 42
  accelerator: gpu
  accumulate_grad_batches: 1
  check_val_every_n_epoch: 10
  checkpoint: null
  dataset_size: 45
  default_root_dir: /pscratch/sd/a/ayz2/logs/
  devices: 4
  dist: true
  learning_rate: 1.0e-06
  log_every_n_steps: 4
  max_epochs: 1000
  pct_start: 0.15
  scheduler: Cosine
  strategy: auto

wandb:
  name: turb3d_ae
  project: ldm_autoencoder