data:
  data_dir: /dev/shm/mesh/
  batch_size: 4
  num_workers: 20
  mode: unstructured
  use_norm: true 
  add_mask: false 
  time_horizon: 25
  padding: True
  max_len: 2060
  scaler: minmax

model:
  aeconfig:
    decoder:
      attn_resolutions:
      - 8
      ch_mult:
      - 1
      - 2
      - 4
      double_z: true
      dropout: 0.0
      gno_coord_dim: 3
      gno_coord_embed_dim: null
      gno_embed_max_positions: null
      gno_mlp_hidden_layers:
      - 32
      - 64
      - 64
      gno_radius: 0.05
      gno_transform_type: linear
      gno_use_torch_scatter: true
      hidden_channels: 64
      in_channels: 32
      num_res_blocks: 2
      out_channels: 3
      resolution: 32
      use_open3d: true
      z_channels: 32
      tanh_out: true
    disc_latent_grid_size: 32
    double_z: true
    encoder:
      attn_resolutions:
      - 8
      ch_mult:
      - 1
      - 2
      - 4
      double_z: true
      dropout: 0.0
      gno_coord_dim: 3
      gno_coord_embed_dim: null
      gno_embed_max_positions: null
      gno_mlp_hidden_layers:
      - 32
      - 64
      - 64
      gno_radius: 0.05
      gno_transform_type: linear
      gno_use_torch_scatter: true
      hidden_channels: 64
      in_channels: 3
      num_res_blocks: 2
      out_channels: 64
      resolution: 32
      use_open3d: true
      z_channels: 32
      tanh_out: true
    latent_grid_size: 32
  lossconfig:
    #disc_ckpt: logs/discriminator.ckpt
    discriminator:
      attn_resolutions:
      - 8
      ch_mult:
      - 1
      - 2
      - 4
      double_z: false
      dropout: 0.0
      gno_coord_dim: 3
      gno_coord_embed_dim: null
      gno_embed_max_positions: null
      gno_mlp_hidden_layers:
      - 32
      - 64
      - 64
      gno_radius: 0.05
      gno_transform_type: nonlinear
      gno_use_torch_scatter: true
      hidden_channels: 64
      in_channels: 3
      num_res_blocks: 2
      out_channels: 64
      resolution: 32
      use_open3d: true
      z_channels: 64
      tanh_out: true
    loss:
      disc_start: 1
      disc_weight: 1.0
      kl_weight: 5.0e-06
      perceptual_weight: 0.0
    lpips:
      model_path: /home/ayz2/ldm_fluids/logs/DPOT/model_S.pth
      model_size: S

training:
  seed: 42
  accelerator: gpu
  accumulate_grad_batches: 1
  check_val_every_n_epoch: 5
  checkpoint: null
  dataset_size: 1000
  default_root_dir: /home/ayz2/ldm_fluids/logs/
  devices:
  - 1
  dist: false
  learning_rate: 1.0e-05
  log_every_n_steps: 100
  max_epochs: 1000
  pct_start: 0.15
  scheduler: Cosine
  strategy: auto

wandb:
  name: GINO_autoencoder_32x8x8x8_disc_normed_batched
  project: ldm_autoencoder