data:
  data_dir: /dev/shm/mesh/
  batch_size: 1
  num_workers: 20
  mode: cylinder
  dataset:
    time_horizon: 25
    padding: True
    max_len: 2060
    use_embed: False
  normalizer:
    use_norm: false  
    scaler: null


model:
    embed_dim: 4
    aeconfig:
        encoder:
            in_channels: 3
            out_channels: 4
            gno_coord_dim: 3
            gno_coord_embed_dim: null
            gno_radius: 0.05
            gno_mlp_hidden_layers: [32, 64, 64]
            gno_transform_type: linear
            gno_use_torch_scatter: True
            hidden_channels: 64
            ch_mult:  [1, 2, 4]
            num_res_blocks: 2
            attn_resolutions: [16]
            dropout:  0.0
            resolution: 64
            z_channels: 4
            double_z: True
            use_open3d: True
        decoder:
            in_channels: 4
            out_channels: 3
            gno_coord_dim: 3
            gno_coord_embed_dim: null
            gno_radius: 0.05
            gno_mlp_hidden_layers: [32, 64, 64]
            gno_transform_type: linear
            gno_use_torch_scatter: True
            hidden_channels: 64
            ch_mult:  [1, 2, 4]
            num_res_blocks: 2
            attn_resolutions: [16]
            dropout:  0.0
            resolution: 64
            z_channels: 4
            double_z: True
            use_open3d: True
        double_z: True
        latent_grid_size: 64
        disc_latent_grid_size: 32
    lossconfig:
        loss: 
            disc_start: 101
            disc_weight: 0.5
            kl_weight: 1.0e-06
            perceptual_weight: 0.0
        lpips:
            model_path: /home/anthonyz/ldm_fluids/logs/DPOT/model_S.pth
            model_size: S
        discriminator:
            in_channels: 3
            out_channels: 16
            gno_coord_dim: 3
            gno_coord_embed_dim: null
            gno_radius: 0.05
            gno_mlp_hidden_layers: [16, 32, 32]
            gno_transform_type: linear
            gno_use_torch_scatter: True
            hidden_channels: 32
            ch_mult:  [1, 2, 4]
            num_res_blocks: 2
            attn_resolutions: [8]
            dropout:  0.0
            resolution: 32
            z_channels: 16
            double_z: False
            use_open3d: True

training:
    accelerator: gpu
    batch_size: 1
    check_val_every_n_epoch: 5
    log_every_n_steps: 100
    checkpoint: null
    dataset_size: 1000
    default_root_dir: /home/anthonyz/ldm_fluids/logs/
    devices: [1]
    dist: False
    learning_rate: 1.0e-5
    max_epochs: 1000
    pct_start: 0.15
    scheduler: Cosine
    strategy: auto
    accumulate_grad_batches: 100
wandb:
    name: GINO_autoencoder
    project: ldm_autoencoder