data:
  data_dir: /dev/shm/mesh/
  batch_size: 1
  num_workers: 20
  mode: unstructured
  use_norm: True
  add_mask: False 
  time_horizon: 25
  padding: False
  max_len: 2060
  scaler: minmax

model:
  aeconfig:
    decoder:
      attn_resolutions:
      - 8
      ch_mult:
      - 1
      - 2
      - 4
      double_z: true
      dropout: 0.0
      gno_coord_dim: 3
      gno_coord_embed_dim: null
      gno_embed_max_positions: null
      gno_mlp_hidden_layers:
      - 32
      - 64
      - 64
      gno_radius: 0.05
      gno_transform_type: linear
      gno_use_torch_scatter: true
      hidden_channels: 64
      in_channels: 32
      num_res_blocks: 2
      out_channels: 3
      resolution: 32
      use_open3d: true
      z_channels: 32
      tanh_out: false
    disc_latent_grid_size: 32
    double_z: true
    encoder:
      attn_resolutions:
      - 8
      ch_mult:
      - 1
      - 2
      - 4
      double_z: true
      dropout: 0.0
      gno_coord_dim: 3
      gno_coord_embed_dim: null
      gno_embed_max_positions: null
      gno_mlp_hidden_layers:
      - 32
      - 64
      - 64
      gno_radius: 0.05
      gno_transform_type: linear
      gno_use_torch_scatter: true
      hidden_channels: 64
      in_channels: 3
      num_res_blocks: 2
      out_channels: 64
      resolution: 32
      use_open3d: true
      z_channels: 32
      tanh_out: false
    latent_grid_size: 32
  embed_dim: 32
  lossconfig:
    discriminator:
      attn_resolutions:
      - 8
      ch_mult:
      - 1
      - 2
      - 4
      double_z: false
      dropout: 0.0
      gno_coord_dim: 3
      gno_coord_embed_dim: null
      gno_embed_max_positions: null
      gno_mlp_hidden_layers:
      - 16
      - 32
      - 32
      gno_radius: 0.05
      gno_transform_type: linear
      gno_use_torch_scatter: true
      hidden_channels: 32
      in_channels: 3
      num_res_blocks: 2
      out_channels: 16
      resolution: 32
      use_open3d: true
      z_channels: 16
    loss:
      disc_start: 101
      disc_weight: 0.5
      kl_weight: 5.0e-06
      perceptual_weight: 0.0
    lpips:
      model_path: /home/anthonyz/ldm_fluids/logs/DPOT/model_S.pth
      model_size: S

training:
  seed: 42
  accelerator: gpu
  accumulate_grad_batches: 100
  check_val_every_n_epoch: 5
  checkpoint: null
  dataset_size: 1000
  default_root_dir: /home/anthonyz/ldm_fluids/logs/
  devices:
  - 2
  dist: false
  learning_rate: 1.0e-05
  log_every_n_steps: 100
  max_epochs: 1000
  pct_start: 0.15
  scheduler: Cosine
  strategy: auto
  #checkpoint: logs/GINO_autoencoder_32x8x8x8_normed2024-07-11T17-51-17/rec_loss=0.05.ckpt

wandb:
  name: GINO_autoencoder_32x8x8x8_normed
  project: ldm_autoencoder