data:
  data_dir: /dev/shm/mesh/
  batch_size: 4
  num_workers: 16
  mode: cylinder
  dataset:
    time_horizon: 25
    padding: True 
    max_len: 2060
    use_embed: False
  normalizer:
    use_norm: true 
    scaler: normal
    stat_path: /dev/shm/mesh/train_normal_stat.pkl
    conditional: False

model:
  aeconfig:
    decoder:
      attn_resolutions:
      - 16
      ch_mult:
      - 1
      - 2
      - 4
      double_z: true
      dropout: 0.1
      gno_coord_dim: 3
      gno_coord_embed_dim: 16
      gno_mlp_hidden_layers:
      - 64
      - 64
      - 64
      - 64
      gno_radius: 0.0425
      gno_transform_type: linear
      gno_use_torch_scatter: true
      hidden_channels: 64
      in_channels: 16
      num_res_blocks: 2
      out_channels: 3
      resolution: 64
      use_open3d: true
      z_channels: 16
      tanh_out: false
    double_z: true
    encoder:
      attn_resolutions:
      - 16
      ch_mult:
      - 1
      - 2
      - 4
      double_z: true
      dropout: 0.1
      gno_coord_dim: 3
      gno_coord_embed_dim: 16
      gno_mlp_hidden_layers:
      - 64
      - 64
      - 64
      - 64
      gno_radius: 0.0425
      gno_transform_type: linear
      gno_use_torch_scatter: true
      hidden_channels: 64
      in_channels: 3
      num_res_blocks: 2
      out_channels: 16
      resolution: 64
      use_open3d: true
      z_channels: 16
      tanh_out: false
    latent_grid_size: 64
  lossconfig:
    kl_weight: 2.0e-07

training:
  seed: 42
  accelerator: gpu
  accumulate_grad_batches: 1
  check_val_every_n_epoch: 5
  checkpoint: null 
  dataset_size: 1000
  default_root_dir: logs/
  devices: 1
  dist: true
  learning_rate: 1.0e-05
  log_every_n_steps: 32
  max_epochs: 1000
  pct_start: 0.15
  scheduler: Cosine
  strategy: auto

wandb:
  name: wandb_name
  project: wandb_project