load_dir: /pscratch/sd/a/ayz2/logs/LDM_Turb3D_DiTHuge_FF2024-11-23T12-15-28/
model_path: /pscratch/sd/a/ayz2/logs/LDM_Turb3D_DiTHuge_FF2024-11-23T12-15-28/last.ckpt

data:
  batch_size: 1
  num_workers: 1
  mode: turb3D
  drop_last: False
  dataset:
    data_dir: /pscratch/sd/a/ayz2/turb3D/data
    time_horizon: 500
    time_window: 240
    time_stride: 5
    use_embed: False 
    first_time_only: False
  normalizer:
    use_norm: true 
    scaler: normal
    stat_path: /pscratch/sd/a/ayz2/turb3D/turb3d_norm_stats.pkl

training:
  accelerator: gpu
  check_val_every_n_epoch: 100
  log_every_n_steps: 4
  checkpoint: null
  dataset_size: 45
  default_root_dir: /pscratch/sd/a/ayz2/logs/
  devices: 4
  strategy: ddp_find_unused_parameters_true
  accumulate_grad_batches: 1
  max_epochs: 5000
  seed: 42

wandb:
    name: LDM_Turb3D_DiTHuge_FF
    project: ldm_diffusion

model:
    base_learning_rate: 5.0e-06
    beta_schedule: linear
    cosine_s: 0.008
    linear_start: 0.00085
    linear_end: 0.012
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    image_size: [6, 12, 3, 3]
    channels: 32
    cond_stage_trainable: True
    scale_factor: 0.2
    clip_denoised: False
    parameterization: eps
    monitor: val/loss
    dist: True

    model_config:
        input_size: [6, 12, 3, 3]
        patch_size: [2, 2, 1, 1]
        in_channels: 32
        hidden_size: 2048
        depth: 28
        num_heads: 16
        mlp_ratio: 4.0
        learn_sigma: False 
        use_cross_attn: True 
        context_dim: 768
        dim: 4

    first_stage_config:
        pretrained_path: /pscratch/sd/a/ayz2/logs/turb3d_ae_small2024-11-22T10-56-51/last.ckpt
        aeconfig:
          encoder:
            attn_resolutions:
            - 16
            ch_mult:
            - 1
            - 2
            - 2
            - 4
            double_z: true
            dropout: 0.0
            hidden_channels: 64
            in_channels: 4
            num_res_blocks: 2
            out_channels: 32
            resolution: [48, 96, 24, 24]
            z_channels: 32
            tanh_out: false
            dim: 4
          decoder:
            attn_resolutions:
            - 16
            ch_mult:
            - 1
            - 2
            - 2
            - 4
            double_z: true
            dropout: 0.0
            hidden_channels: 64
            in_channels: 32
            num_res_blocks: 2
            out_channels: 4
            resolution: [48, 96, 24, 24]
            z_channels: 32
            tanh_out: false
            dim: 4
        lossconfig:
          kl_weight: 2.0e-07

        training:
            dist: True

    cond_stage_config:
        conditional: True
        out_dim: 768
        pretrained: False
        use_fourier: False
        encoder:
          attn_resolutions:
          - 16
          ch_mult:
          - 1
          - 2
          - 4
          - 4 
          double_z: false
          dropout: 0.0
          hidden_channels: 128
          in_channels: 4
          num_res_blocks: 2
          out_channels: 768
          cond_channels: 128
          resolution: [96, 24, 24]
          z_channels: 768
          tanh_out: false
          dim: 3 # 3 dimensional input since condition on first frame