data:
  data_dir: /home/ayz2/data/NavierStokes-2D-conditoned/
  #data_dir: /home/anthonyz/data/ns2D/
  batch_size: 3
  num_workers: 20
  mode: ns2D
  drop_last: True
  dataset:
    data_path: /home/ayz2/data/NavierStokes-2D-conditoned
    #data_path: /data/zijie_data/pde_data/NavierStokes-2D-conditoned
    delta_t: 1
    downsample: 1
    trajlen: 48
    num_training_trajs: -1   # use all for each buoyancy
    num_testing_trajs: -1
    start_time: 0   # for testing
  normalizer:
    use_norm: true 
    scaler: minmax
    stat_path: /home/ayz2/data/ns2D/train_ns2D_minmax_128_stat.pkl

training:
  seed: 42
  accelerator: gpu
  accumulate_grad_batches: 1
  check_val_every_n_epoch: 5
  checkpoint: null
  dataset_size: 2496
  default_root_dir: /home/ayz2/ldm_fluids/logs/
  devices: 3
  dist: true
  learning_rate: 1.0e-05
  log_every_n_steps: 100
  max_epochs: 1000
  pct_start: 0.15
  scheduler: Cosine
  strategy: auto

model:
  aeconfig:
    decoder:
      attn_resolutions:
      - 16
      ch_mult:
      - 1
      - 2
      - 4
      - 4
      double_z: true
      dropout: 0.0
      hidden_channels: 64
      in_channels: 16
      num_res_blocks: 2
      out_channels: 3
      cond_channels: 1
      resolution: [48, 128, 128]
      z_channels: 16
      tanh_out: true
    encoder:
      attn_resolutions:
      - 16
      ch_mult:
      - 1
      - 2
      - 4
      - 4
      double_z: true
      dropout: 0.0
      hidden_channels: 64
      in_channels: 3
      num_res_blocks: 2
      out_channels: 16
      cond_channels: 1
      resolution: [48, 128, 128]
      z_channels: 16
      tanh_out: true
  lossconfig:
    kl_weight: 2.0e-07

wandb:
  name: Grid_AE_16_minmax_tanh_large
  project: ldm_autoencoder