load_dir: logs/profiles/Dil_Resnet/
model_path: logs/profiles/Dil_Resnet/last.ckpt
model_name: dil_resnet

data:
  batch_size: 8
  num_workers: 20
  mode: ns2D
  dataset:
    data_dir: /home/ayz2/data/NavierStokes-2D-conditoned
    delta_t: 1
    downsample: 1
    trajlen: 48
    num_training_trajs: -1   # use all for each buoyancy
    num_testing_trajs: -1
    start_time: 0   # for testing
    use_embed: False 
  normalizer:
    use_norm: true 
    scaler: normal
    stat_path: /home/ayz2/data/ns2D/train_ns2D_normal_128_stat.pkl

model:
  name: dil_resnet
  dil_resnet:
    n_input_scalar_components: 3
    n_input_vector_components: 0
    n_output_scalar_components: 3
    n_output_vector_components: 0
    time_history: 1
    time_future: 1
    num_blocks: [2, 2, 2, 2]
    time_future: 1
    time_history: 1
    hidden_channels: 256
    cond_channels: 1

training:
  seed: 42
  accelerator: gpu
  accumulate_grad_batches: 4
  check_val_every_n_epoch: 5
  checkpoint: null
  dataset_size: 2496
  default_root_dir: logs/
  devices: 1
  dist: false
  learning_rate: 1.0e-4
  log_every_n_steps: 100
  max_epochs: 50
  pct_start: 0.15
  scheduler: Cosine
  strategy: auto
  gradient_clip_val: 1.0

wandb:
  name: Dil_Resnet_NS2D_large
  project: ldm_baselines