load_dir: /pscratch/sd/a/ayz2/logs/DilResnet_turb3D2024-11-20T02-21-10/
model_path: /pscratch/sd/a/ayz2/logs/DilResnet_turb3D2024-11-20T02-21-10/last.ckpt

data:
    batch_size: 1
    num_workers: 4
    mode: turb3D
    drop_last: False
    dataset:
      data_dir: /pscratch/sd/a/ayz2/turb3D/data
      time_horizon: 500
      time_window: 240
      time_stride: 5
    normalizer:
      use_norm: true 
      scaler: normal
      stat_path: /pscratch/sd/a/ayz2/turb3D/turb3d_norm_stats.pkl

model:
  name: dil_resnet
  dil_resnet:
    n_input_scalar_components: 1
    n_input_vector_components: 1
    n_output_scalar_components: 1
    n_output_vector_components: 1
    time_history: 1
    time_future: 1
    hidden_channels: 128
    num_blocks: [2, 2, 2, 2]
    dim: 3

training:
  seed: 42
  accelerator: gpu
  accumulate_grad_batches: 4
  check_val_every_n_epoch: 50
  checkpoint: null
  dataset_size: 45
  default_root_dir: /pscratch/sd/a/ayz2/logs/
  devices: 1
  dist: false
  learning_rate: 1.0e-05
  log_every_n_steps: 18
  max_epochs: 10000
  pct_start: 0.15
  scheduler: Cosine
  strategy: auto

wandb:
  name: DilResnet_turb3D
  project: ldm_baselines