load_dir: /pscratch/sd/a/ayz2/logs/FNO_turb3D2024-11-17T14-36-28/
model_path: /pscratch/sd/a/ayz2/logs/FNO_turb3D2024-11-17T14-36-28/model_epoch=549-val/rollout_error=0.797.ckpt

data:
    batch_size: 1
    num_workers: 4
    mode: turb3D
    drop_last: False
    dataset:
      data_dir: /pscratch/sd/a/ayz2/turb3D/data
      time_horizon: 500
      time_window: 240
      time_stride: 5
    normalizer:
      use_norm: true 
      scaler: normal
      stat_path: /pscratch/sd/a/ayz2/turb3D/turb3d_norm_stats.pkl

model:
  name: fno
  fno:
    n_modes: [16, 16, 16]
    hidden_channels: 192
    in_channels: 4
    out_channels: 4
    lifting_channels: 192
    projection_channels: 192
    n_layers: 6

training:
  seed: 42
  accelerator: gpu
  accumulate_grad_batches: 4
  check_val_every_n_epoch: 50
  checkpoint: null
  dataset_size: 45
  default_root_dir: /pscratch/sd/a/ayz2/logs/
  devices: 1
  dist: false
  learning_rate: 1.0e-05
  log_every_n_steps: 18
  max_epochs: 10000
  pct_start: 0.15
  scheduler: Cosine
  strategy: auto

wandb:
  name: FNO_turb3D
  project: ldm_baselines