load_dir: logs/ldm_ns2D/text/DiTSmall/
model_path: /home/ayz2/ldm_fluids/logs/ldm_ns2D/text/DiTSmall/last.ckpt
phiflow: True 

data:
    batch_size: 4
    num_workers: 16
    mode: ns2D
    drop_last: True
    dataset:
      data_dir: /home/ayz2/data/NavierStokes-2D-conditoned
      delta_t: 1
      downsample: 1
      trajlen: 48
      num_training_trajs: -1   # use all for each buoyancy
      num_testing_trajs: -1
      start_time: 0   # for testing
      use_embed: True
    normalizer:
      use_norm: true 
      scaler: normal
      stat_path: /home/ayz2/data/ns2D/train_ns2D_normal_128_stat.pkl

training:
    accelerator: gpu
    check_val_every_n_epoch: 10
    log_every_n_steps: 32
    checkpoint: null
    dataset_size: 2496
    default_root_dir: logs/
    devices: 1
    strategy: auto
    accumulate_grad_batches: 1
    max_epochs: 1000
    seed: 42
    ema_decay: null
    ema_every_n_steps: 1

wandb:
    name: LDM_NS2D_DiT_text
    project: ldm_diffusion

model:
    base_learning_rate: 1.0e-05
    beta_schedule: linear
    cosine_s: 0.008
    linear_start: 0.00085
    linear_end: 0.012
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    image_size: [6, 16, 16]
    channels: 16
    cond_stage_trainable: True
    scale_factor: 0.2
    clip_denoised: False
    parameterization: eps
    monitor: val/loss
    dist: True

    scheduler_config:
        scheduler: cosine

    model_config:
        input_size: [6, 16, 16]
        patch_size: [1, 2, 2]
        in_channels: 16
        hidden_size: 512
        depth: 24
        num_heads: 16
        mlp_ratio: 4.0
        learn_sigma: False 
        use_cross_attn: True 
        context_dim: 768
        dim: 3

    first_stage_config:
        pretrained_path: logs/ns2D/new_rec_loss=0.01.ckpt
        aeconfig:
          decoder:
            attn_resolutions:
            - 16
            ch_mult:
            - 1
            - 2
            - 4
            - 4
            double_z: true
            dropout: 0.0
            hidden_channels: 64
            in_channels: 16
            num_res_blocks: 2
            out_channels: 3
            cond_channels: 1
            resolution: [48, 128, 128]
            z_channels: 16
            tanh_out: false
          encoder:
            attn_resolutions:
            - 16
            ch_mult:
            - 1
            - 2
            - 4
            - 4
            double_z: true
            dropout: 0.0
            hidden_channels: 64
            in_channels: 3
            num_res_blocks: 2
            out_channels: 16
            cond_channels: 1
            resolution: [48, 128, 128]
            z_channels: 16
            tanh_out: false
        lossconfig:
          kl_weight: 2.0e-07

        training:
            dist: True

    cond_stage_config:
        conditional: True